setwd("/Users/GreenTea/Desktop")
WHO<-read.csv("mvtWeek1.csv")
nrow(WHO)
summary(WHO$Arrest)
summary(WHO$LocationDescription)
head(WHO$Date)
DateConvert = as.Date(strptime(WHO$Date, "%m/%d/%y %H:%M"))
median(DateConvert)
WHO$Weekday = weekdays(DateConvert)
WHO$ID<-as.character(WHO$ID)
tapply(WHO$Arrest,WHO$Month,sum)
summary(WHO)
table(WHO$Weekday)
hist(WHO$Date, breaks=100)
WHO$Date = DateConvert
boxplot(Date ~ Arrest, data = WHO)
table(WHO$Weekday, WHO$LocationDescription=="DRIVEWAY - RESIDENTIAL")
subset(WHO,WHO$Year==2001&WHO$Arrest=="FALSE")
tapply(WHO$LocationDescription,WHO$Arrest,sum)
table
550/(550+13542)
sort(table(WHO$LocationDescription))
who1<-subset(WHO,WHO$LocationDescription=="STREET" | WHO$LocationDescription=="PARKING LOT/GARAGE(NON.RESID.)"| WHO$LocationDescription=="ALLEY" | WHO$LocationDescription=="GAS STATION" | WHO$LocationDescription=="DRIVEWAY - RESIDENTIAL")
who1$LocationDescription = factor(who1$LocationDescription)
str(who1)
WHO$LocationDescription<-as.character(WHO$LocationDescription)
setwd("/Users/GreenTea/Downloads")
IBM<-read.csv("IBMStock.csv")
GE<-read.csv("GEStock.csv")
ProcterGamble<-read.csv("ProcterGambleStock.csv")
CocaCola<-read.csv("CocaColaStock.csv")
Boeing<-read.csv("BoeingStock.csv")
IBM$Date = as.Date(IBM$Date, "%m/%d/%y")
GE$Date = as.Date(GE$Date, "%m/%d/%y")
CocaCola$Date = as.Date(CocaCola$Date, "%m/%d/%y")
ProcterGamble$Date = as.Date(ProcterGamble$Date, "%m/%d/%y")
Boeing$Date = as.Date(Boeing$Date, "%m/%d/%y")
summary(ProcterGamble)
sd(ProcterGamble$StockPrice)
plot(CocaCola$Date,CocaCola$StockPrice,type = "l",col="red")
lines(ProcterGamble$Date, ProcterGamble$StockPrice,col="blue",lty=2)
abline(v=as.Date(c("2000-03-01")), lwd=2)
abline(v=as.Date(c("1983-01-01")), lwd=2)
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(ProcterGamble$Date[301:432], ProcterGamble$StockPrice[301:432],col="blue")
lines(IBM$Date[301:432], IBM$StockPrice[301:432],col="green")
lines(GE$Date[301:432], GE$StockPrice[301:432],col="yellow")
lines(Boeing$Date[301:432], Boeing$StockPrice[301:432],col="purple")
abline(v=as.Date(c("1997-09-01")), lwd=2)
abline(v=as.Date(c("1997-11-01")), lwd=2)
tapply(IBM$StockPrice, months(IBM$Date), mean)
tapply(GE$StockPrice, months(GE$Date), mean)
tapply(CocaCola$StockPrice, months(CocaCola$Date), mean)
tapply(Boeing$StockPrice, months(Boeing$Date), mean)
tapply(ProcterGamble$StockPrice, months(ProcterGamble$Date), mean)
summary(IBM)
CPS<-read.csv("CPSData.csv")
table(CPS$Industry)
sort(table(CPS$State)) 
table(CPS$Citizenship)
1-7590/(116639+7073)
tapply(CPS$Hispanic,CPS$Race,sum)
summary(CPS)
is.na(CPS$Married)
table(CPS$Age, is.na(CPS$Married))
table(CPS$State,is.na(CPS$MetroAreaCode))
sort(tapply(is.na(CPS$MetroAreaCode),CPS$State,mean))
MetroAreaMap<-read.csv("MetroAreaCodes.csv")
CountryMap<-read.csv("CountryCodes.csv")
CPS = merge(CPS, MetroAreaMap, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
sort(table(CPS$MetroArea))
sort(tapply(CPS$Hispanic,CPS$MetroArea,mean))
sort(tapply(CPS$Race == "Asian" ,CPS$MetroArea,mean))
sort(tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean,na.rm=TRUE))
CPS = merge(CPS, CountryMap, by.x="CountryOfBirthCode", by.y="Code", all.x=TRUE)
summary(CPS$Country)
tapply(CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA" ,CPS$Country, sum,na.rm=TRUE)
nrow(CPS[CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA"&is.na(CPS$Country),])
sum(which(CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA"))
table(CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA", CPS$Country != "United States")
